// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwTPcvv5CzKvgt9F9inWcJMTrWw5KXWYo',
    appId: '1:366598389196:web:684023522d38d68e9db169',
    messagingSenderId: '366598389196',
    projectId: 'dog-book-5454e',
    authDomain: 'dog-book-5454e.firebaseapp.com',
    storageBucket: 'dog-book-5454e.firebasestorage.app',
    measurementId: 'G-GLRP761P0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSZRfc86AVAIu_Pph-JTLphWOVKvoeAyk',
    appId: '1:366598389196:android:78d885b28169048b9db169',
    messagingSenderId: '366598389196',
    projectId: 'dog-book-5454e',
    storageBucket: 'dog-book-5454e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqXoQUdQMao-I-2wEubaFKP8xhml_YT2k',
    appId: '1:366598389196:ios:7873340f5239fb359db169',
    messagingSenderId: '366598389196',
    projectId: 'dog-book-5454e',
    storageBucket: 'dog-book-5454e.firebasestorage.app',
    iosBundleId: 'com.example.dogBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqXoQUdQMao-I-2wEubaFKP8xhml_YT2k',
    appId: '1:366598389196:ios:7873340f5239fb359db169',
    messagingSenderId: '366598389196',
    projectId: 'dog-book-5454e',
    storageBucket: 'dog-book-5454e.firebasestorage.app',
    iosBundleId: 'com.example.dogBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwTPcvv5CzKvgt9F9inWcJMTrWw5KXWYo',
    appId: '1:366598389196:web:a8c10897bf0d3e079db169',
    messagingSenderId: '366598389196',
    projectId: 'dog-book-5454e',
    authDomain: 'dog-book-5454e.firebaseapp.com',
    storageBucket: 'dog-book-5454e.firebasestorage.app',
    measurementId: 'G-1LWVPV1JX6',
  );
}
